package.json
=> package.json dependency

openshift/templates/nodejs.json
Also cleanup needless bits and fixed a broken reference to repo URL.
@bparees @mfojtik PTAL
=> Update template to API v1

openshift/templates/nodejs.json
@bparees Externally reference image stream in openshift namespace
=> use external image stream for builder image

openshift/templates/nodejs.json
Changing Django, Rails and Node.js examples.
Tested all examples/templates with creating a project for each, deploying and curl'ing.
@bparees PTAL
=> Standardize templates across examples

openshift/templates/nodejs.json
=> Add SOURCE_REPOSITORY_REF parameter

openshift/templates/nodejs.json
=> Set build output to latest ImageStreamTag

README.md
=> Rename osc -> oc

openshift/templates/nodejs-mongodb.json
=> Add database template

openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
=> Pass relevant ENV VARs to application container

openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
=> add default memory limit for deployments

openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
@bparees @danmcp FYI / PTAL
these changes stem from discussion on aos-scalability and are explicit direction from @danmcp
=> bump all template mem limits to 512 Mi

openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
=> edits consistent with UI philosophy

openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
@bparees Fixes https://github.com/openshift/origin/issues/3571
=> parameterize name

openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
part of openshift/origin#3563
@bparees PTAL
=> parameterize IS namespace

.gitignore, openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json, package.json, server.js, tests/app_test.js
fixes https://github.com/openshift/nodejs-ex/issues/32
fixes https://github.com/openshift/nodejs-ex/issues/18
@bparees @rhcarvalho PTAL.
tested by building it in origin 
_works on my machine_ .
=> add unit tests for post commit hook

README.md
Fresh PR here, sorry for the confusion -- no unreviewed changes here.
=> Added MongoDB notes

openshift/templates/nodejs-mongodb.json
=> change BC ICT to automatic=true (more deterministic)

views/index.html
=> update webhook instructions

openshift/templates/nodejs-mongodb-persistent.json
=> Adds NodeJS/MongoDB template with persistent storage.

openshift/templates/nodejs-mongodb-persistent.json, openshift/templates/nodejs-mongodb.json
@bparees adding the annotation to all the quickstarts, testing on the hackday cluster :)
=> group services in quickstarts

openshift/templates/nodejs-mongodb-persistent.json, openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
@bparees Please review and merge
=> Updates template display name, tags, description, message, and grouping

openshift/templates/nodejs-mongodb-persistent.json, openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
@bparees 
In addition to moving secrets, I'm removing database parameters from non-db templates.
=> Moving credentials into secrets

openshift/templates/nodejs-mongodb-persistent.json
=> updating to use secrets

openshift/templates/nodejs-mongodb-persistent.json, openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
Reverts openshift/nodejs-ex#112
=> re-enable nodejs:6 in templates

openshift/templates/nodejs-mongodb-persistent.json, openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
https://bugzilla.redhat.com/show_bug.cgi?id=1365656
@bparees ptal
=> Updating GITHUB_WEBHOOK_SECRET description

README.md
=> Adding compatibility section

openshift/templates/nodejs-mongodb-persistent.json, openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
please merge after https://github.com/openshift/origin/pull/15402
=> add template completion detection

server.js
=> Update server.js - remove fs module

openshift/templates/nodejs-mongodb-persistent.json, openshift/templates/nodejs-mongodb.json, openshift/templates/nodejs.json
xref https://github.com/openshift/origin/pull/17215
=> remove expose annotations from quickstarts and add bindable: false

server.js
debugging for https://github.com/openshift/origin/issues/17649
=> add debug if error happens in count()

openshift/templates/nodejs-mongodb-persistent.json
https://github.com/openshift/origin/pull/17922#pullrequestreview-86940496
=> Remove ' (Persistent)'

openshift/templates/nodejs.json
Got rid of a duplicate key
<done over Github UI>
=> Fix invalid JSON in template: nodejs.json

README.md
@bparees can you please suggest if this needs any changes? Ref: #169
=> Add documentation about using minishift

openshift/templates/nodejs-mongodb-persistent.json, openshift/templates/nodejs-mongodb.json
fixes: https://github.com/openshift/origin/issues/19379
=> mongodb openshift template: generalize probes

openshift/templates/nodejs-mongodb-persistent.json, openshift/templates/nodejs-mongodb.json
add example templates for ppc64le imagestreams
=> add example templates for ppc64le imagestreams

openshift/templates/nodejs.json
=> switch nodejs template to default to nodejs v12

openshift/templates/nodejs-postgresql-persistent.json, openshift/templates/nodejs.json
=> Migrate from DeploymentConfig to Deployment

.github/workflows/openshift-tests.yml
=> Add Testing Farm as GitHub Action for running tests

Makefile, tests/test_nodejs.py
Add tests for nodejs-ex repository.
It tests imported imagestreams against this repo.
=> Add tests for nodejs-ex repository.

.github/workflows/openshift-tests.yml
=> Switch to RHEL-9
